# Generated by Django 3.2.6 on 2021-09-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('category', models.CharField(blank=True, max_length=30, null=True)),
                ('ingredients', models.CharField(blank=True, max_length=30, null=True)),
                ('instructions', models.CharField(blank=True, max_length=30, null=True)),
                ('measures', models.CharField(blank=True, max_length=30, null=True)),
                ('slug', models.SlugField(default='test')),
                ('image_url', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
